### ISSUE TITLE
Implement bulk API

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#103]
It would be **tremendously useful** if itwêwina could ping an endpoint on the `speech-db` that would search for many _exact_ wordforms at once, and return the URLs and metadata for the recordings.

Rationale:

 1. more efficient to make one BIG query than hundreds of small queries, with some of them failing

For example, itwêwina would make requests that resemble the following:

```http
GET /api/bulk?q=mistik&q=minahik&q=waskay&q=mîtos&q=mistikow&q=mêstan
Host: speech-db.altlab.app

```

Or even with a `POST'd` JSON body:

```http
POST /api/bulk
Host: speech-db.altlab.app
Content-type: appplication/json

{
   "wordforms": ["mistik", "minahik", "waskway", "mîtos", "mêstan"]
}
```

---

The `speech-db` would return a JSON body featuring all wordforms that matched, along with URLs to the recording, similar to the existing API:

```json
{
  "matched_recordings": [
    {
      "wordform": "mistik",
      "recording_url": "https://speech-db.altlab.app/media/audio/d23ab1dfec29b3b7f45442437d9dd7cba22b3e9c05056f257d4107d9a11885da.m4a",
      "quality": "best",
      "speaker_name": "Jerry Roasting",
      "speaker_bio_url": "https://www.altlab.dev/maskwacis/Speakers/JER.html",
      "anonymous": false,
      "speaker": "JER",
      "dialect": "Maskwacîs",
      "gender": "M"
    }
  ],
  "not_found": ["minahik", "waskway", "mîtos", "mêstan"]
}
```

Additional comments:

 - The API should prioritize "best" quality recordings, followed by "good" quality recordings. It should NOT return "bad" quality recordings. It _may_ return recordings that do not have a quality marker.
 - If this is implemented, it **obsoletes** #75, which can be closed and marked as `wontfix` 😁

**Comment by nienna73** [comment]
@eddieantonio I have a vague recollection of us implementing this. Did we actually make any progress on this issue?

**Comment by eddieantonio** [comment]
@nienna73 not at all. There needs to be a new URL and API **with documentation and tests** that can be given a list of _exact_, validated wordforms with normatized spelling (no spelling relaxation). Does the code currently have a "normatized spelling" field for the transcription? That is, is there a column that is guarenteed to spell the transcription in perfect SRO?

**Comment by eddieantonio** [comment]
@nienna73: do we have enough transcriptions in the database with **perfect** SRO in it? I think we should probably get this feature rolled out soon, so that we can improve itwêwina. We can pair on this if you'd like.

**Comment by nienna73** [comment]
We did this!
