### ISSUE TITLE
Automatically insert information for certain speakers

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#104]
We currently need to rebuild the database every time we want to extract recordings; however, this _deletes the names and genders of speakers in the database!_ So this information should be placed into the database, perhaps during the import process.

@nienna73, I'll prepare this seed data and send it to you!

**Comment by nienna73** [comment]
@eddieantonio Do you have an update on the seed data? I have a feeling it will help me with #72

**Comment by eddieantonio** [comment]
Haha, I DM'd it to you on Slack a while ago! I'll prepare it again and send it to you on some place more permanent. Do you think this data is okay to store in the repository itself?

**Comment by nienna73** [comment]
...oops. Considering we present this information on the `/speakers` page, it's probably fine to have it in the repo itself, yeah. I'm happy to add it myself, if you just want to send it to me over Slack again.
