### ISSUE TITLE
Default user type

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/recording-validation-interface#128]
Users should be assigned a default role when registering a new account.

The default role is "community member", which has permission to edit the transcription and translation, but not the analysis of an entry.

Users can either a) select a flag during the registration process to request "linguist" access or b) have to email or message a developer to be given "linguist" access.

**Comment by nienna73** [comment]
We changed the wording of the sign up process so that we now have 4 user groups:
* Language Expert
* Linguist
* Instructor
* Learner

@aarppe which of these roles should be the default role if one is not selected?
I'm leaning towards making "Learner" the default role as they have the least privileges.

**Comment by aarppe** [comment]
Yes, I'd consider `Learner` the default case, as that would be comparable to an occasional "browser".

**Comment by nienna73** [comment]
This is resolved.
