### ISSUE TITLE
Incorrect speaker codes

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#152]
For some of the recordings, they are nicely aligned and correctly linked with their transcription, but the speaker codes are mostly wrong, e.g.

https://speech-db.altlab.app/search/?query=s%C3%AEs%C3%AEkwas

Here, all the recordings are attributed to BL2, but he is the actual speaker only on the last four recordings; the preceding other speakers (in order) are: ANN? (2 snippets) and HAR (2 snippets), (and then BL2).

**Comment by eddieantonio** [comment]
We need to do a reimport for this once #153 is merged.

**Comment by nienna73** [comment]
#153 has been merged and I've attempted to re-run the extraction process since, which is how we will eventually solve this issue. There are still a few lingering issues related to the metadata and/or the data inconsistencies. I think we need to solve #101 before I can truly solve this issue.

**Comment by nienna73** [comment]
I would estimate that around 80% of the incorrect speaker codes have been dealt with and the rest are being investigated.

**Comment by nienna73** [comment]
Through the new "wrong speaker" button, we've been able to address the majority of these cases. Since we now have a long-term solution to this problem, I'm closing this issue.
