### ISSUE TITLE
Enable linguists to directly mark bad quality for recordings

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#155]
Since we're now running into, when searching for example case, a number of recordings for which the quality is compromised, it would be useful for the linguist in question to be able to mark in the speech database the quality of such a recording as `bad`, so that this won't turn up in _itwêwina_. So, in this case, this wouldn't require quality marking in the original annotations. A good poster-child for this would be _wâpamêw_, as in: https://itwewina.altlab.app/word/w%C3%A2pam%C3%AAw/

This quality assessment might be something that we could do for the most frequent of words and typical example cases that we often look up (and which others might due as well due to frequency/centrality of the word/concept).

**Comment by nienna73** [comment]
The functionality for this already exists and Linguists and Language Experts are the only ones capable of marking recording quality. This function isn't on the production server yet, but I'm confident that this issue will be resolved once it is.

**Comment by nienna73** [comment]
I think this has been resolved.
