### ISSUE TITLE
Mark words already in the Maskwacîs Dictionary

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#165]
As a more precise task leading up to #38, for the just shy of 9000 entries already in the Maskwacîs Dictionary, these do not require validation of their English translations, as that was done at the time of the collection of that glossary. Nevertheless, we will need to standardize their orthographical form as a separate task.

**Comment by nienna73** [comment]
This has been done, though I don't think it's quite right yet. Currently, a word gets marked as already existing and then does not need its spelling validated by a user. However, the English translation does not get set to the version that's already in the dictionary, this is yet to be implemented.

**Comment by nienna73** [comment]
English translations are saved as of several weeks ago.
The only remaining potential issue is homograph disambiguation, which can be addressed in a separate issue.
