### ISSUE TITLE
Allow speakers to provide a better English translation for a Cree word form / sentence

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#175]
If the speaker indicates there is something wrong with the English translation (in responding YES to the question 'Is this translation accurate' and clicking 'There's a better translation for this Cree word'), they should then be able to enter that improvement in a field.

We'd want to keep Cree and English suggestions as separate from each other.

**Comment by nienna73** [comment]
I believe this has been implemented.
