### ISSUE TITLE
Allow users to provide a better spelling for a Cree word / sentence

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#176]
Add an option for the speakers to provide a better / more accurate spelling for the Cree words and sentences.

Of course, a question here is whether this is in effect already implemented on the linguist version of the interface.

**Comment by nienna73** [comment]
I believe this has been addressed with the suggestion pop-up. It's only a suggestion though: a linguist still has to go in and make the change permanent.
