### ISSUE TITLE
Remove white space characters from the edges of the MD transcription field

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#200]
Currently, many English translations have in particular some unnecessary initial (and perhaps final) white characters - this may apply to the Cree transcriptions as well. This may sometimes be a reason that seemingly exactly similar Cree words or phrases get treated as different entries in the speech-db. The remedy here would be to automatically remove any such white-space characters from both edges of the English translation and Cree transcription fields.

**Comment by nienna73** [comment]
The series of actions that lead to this issue has been changed. This issue is somewhat resolved as a result of this workflow change.
