### ISSUE TITLE
Linguistic revision status should be more obvious

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#217]
When reviewing my linguistic validation work, it is not easily evident whether I've touched some entry, or what changes I'va made. E.g. for _natimihk_, at the top I can first see tens of speller suggestions, many of which are irrelevant, i.e.

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/15003407/122499113-8ace4d80-cfad-11eb-85a6-0729d81b41f8.png">

... , and only at the bottom do I see that I've reviewed the entry and provided a linguistic analysis, i.e.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/15003407/122499179-ae919380-cfad-11eb-8c44-e6dbab987a19.png">

In particular, that a linguist has provided or chosen some linguistic analysis should be apparent high up - this would also suggest (though not necessarily guarantee) that the transcription itself has been standardized.

**Comment by nienna73** [comment]
In #260 I added a note to the top of this page that says "This entry was last edited by {user} on {date}" so you can easily see if you've already looked at it.
