### ISSUE TITLE
Linguistic analysis should concern the wordform, not the lemma

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#218]
While the standardized spellings that are shown concern the particular word forms, the linguistic analysis seems to concern the lemma, not the word-form, cf.

<img width="986" alt="image" src="https://user-images.githubusercontent.com/15003407/122511037-e0adf000-cfc3-11eb-8b1b-65fb64c88978.png">

Here, the analysis from the FST that is associated with the wordform: _askipwâwa_ is `askipwâwi+N+I+Pl`.

**Comment by nienna73** [comment]
I solved this issue in #260 by running the inflected wordform through the HFST optimized lookup and using that analysis instead.
