### ISSUE TITLE
Server Error when setting a wrong speaker as "I don't know"

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#238]
I got this 500 Server Error when I tried to mark a wrong speaker with the "I don't know" option:

https://user-images.githubusercontent.com/2294397/126205103-d31f70a2-1e3c-43f9-aed6-0a8562bc2652.mov

**EDIT**: reproduce by going to this URL: https://speech-db.altlab.app/search/?query=w%C3%AEtask%C3%AEwin then setting the first clicking on the first recording for "wîtaskîwin" as "wrong speaker" and clicking submit.

**Comment by nienna73** [comment]
I am unable to replicate this issue and as such am going to assume I fixed it (which I believe I did a number of PRs ago).
This was likely happening due to information that no longer being submitted by the form, but the code was still trying to access it.
