### ISSUE TITLE
What format are the new recordings stored in?

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#254]
@nienna73 Are the new recordings stored first in a non-lossy format such as WAV? (even if they're later on converted into some more compressed format such as MP4.)

**Comment by nienna73** [comment]
We're currently storing two copies of each recording: one .wav file to preserve full quality, and one .m4a file as it's much smaller and easier to serve up in the service.

We're also saving a JSON file for each recording with the following information:
- Username of person who recorded it
- Full name of person who recorded it
- Date and time of the recording
- Cree word
- English word
- Audio file name

We can add more information to this JSON metadata if we desire.

**Comment by nienna73** [comment]
@aarppe if all your questions about recording format have been answered, please close this issue. Otherwise I can answer other questions here so we have everything in one place.

**Comment by aarppe** [comment]
My original question was addressed.
