### ISSUE TITLE
Autofill fields when provided from language-expert review

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#255]
If the (Cree) transcription or (English) translation fields are not empty, use those to autofill the fields when a recording is selected for further review, e.g.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/15003407/129287148-89199575-9065-4112-8f5c-be10d363b4a3.png">

In the above, the language expert review already provides both the Cree transcription and the English translation, so that these need no longer be re-typed. Nevertheless, after autofill, we still want to allow the linguist reviewer to edit either field, or provide missing content when none was provided.

The same autofill would apply to correcting the speaker code as well.

**Comment by nienna73** [comment]
This was implemented in #260
