### ISSUE TITLE
2 out of 3 speaker codes are wrong for kêyapic

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#257]
In the below screenshot:

<img width="295" alt="image" src="https://user-images.githubusercontent.com/15003407/129493750-8754d487-f090-4fb5-9732-981cd1a64831.png">

... Arlene Makinaw and Brian Lightning appear to have been mixed (but not Harley Simon), which may be due to a broader miscoding for the session in question.

**Comment by aarppe** [comment]
@emcgarve You could check that the speaker codes for the session is question are correctly assigned.

**Comment by aarppe** [comment]
Having checked a few items for the session in question 2018-05-02-AM/PM-OFF, it appears that the culprit here is that ARL and BRI had switched mics for the afternoon, i.e. that the AM speaker code assignment is correct, but then swapped for the afternoon.

**Comment by nienna73** [comment]
This issue has been resolved. @aarppe I found your issues filed in speech-db and addressed the issue there. All the speaker codes for this particular word should now be correct.
