### ISSUE TITLE
Create interface for validating translations ONLY

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#26]
In this step, we can judge recording quality too!

Do **NOT** display the transcription!

**EDIT**: I have more ideas about this:

Create an interface that allows an iPad user to quickly hear the recording, and validate:

 1) Part of speech
  * uses a Cree taxonomy of part of speech rather than the Algonquinist traditional taxonomy
 2) The translation itself
  * Highlights arguments (when it's a verb) or possessor (when it's a dependent noun)

![NuevoDocumento 2019-10-07 15 12 56](https://user-images.githubusercontent.com/2294397/66349101-5750aa00-e915-11e9-9eef-b550a2f07ecc.jpg)

(Ignore the fact that I chose the word "nêpêwimêw" as the word to validate!)

**Comment by nienna73** [comment]
I'm not sure I follow this issue. 

Does the new UI do this?

Is this something we still want to do?

**Comment by aarppe** [comment]
I presume this is a functionality that was intended for the community language Experts. So if this is implemented for that user groups, then this should have been taken care of.

**Comment by eddieantonio** [comment]
I think there are other issues that take care of the functionality requested here.
