### ISSUE TITLE
Add "admin" link for administrators

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#32]

**Comment by nienna73** [comment]
What is the purpose of creating an "admin" link for administrators?

**Comment by eddieantonio** [comment]
To access the Django admin interface. There, admins (like Antti) can access quick analytics (how many recordings are there) and edit things like speaker bios directly.

**Comment by nienna73** [comment]
Do we need to manually add the `/admin` path, or is Django doing that for us? Cause I think Django is doing that for us.

**Comment by eddieantonio** [comment]
Here is the line that adds the admin path to our URLs:

https://github.com/UAlbertaALTLab/recording-validation-interface/blob/dbc91823a265aa4a061cad27bb006f66dcae007f/recvalsite/urls.py#L22

Django does _not_ insert this path automatically, but we've already done it!

---

However a link that is available to administrator accounts (I'm not sure which roles _should_ be able to access the admin panel) should appear in the header, next to "logout".

**Comment by nienna73** [comment]
I figured it would just be a handful of ALTLab members that need access to the django admin interface. I'm hesitant to show a link to that interface on the main page as people might think they're missing out on some privileges or that they need admin access to perform certain actions.

**Comment by eddieantonio** [comment]
A solution to this is to only show the link to users that are logged in
and have the appropriate role. 

—
Eddie Antonio Santos
***@***.*** ***@***.***>
***@***.*** ***@***.***>
<https://eddieantonio.ca/>

On March 24, 2021, GitHub Notifications ***@***.***>
wrote:
> I figured it would just be a handful of ALTLab members that need
> access to the django admin interface. I'm hesitant to show a link to
> that interface on the main page as people might think they're missing
> out on some privileges or that they need admin access to perform
> certain actions.
>

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/UAlbertaALTLab/recording-validation-
interface/issues/32#issuecomment-806031020>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AARQE7MFVAQSVH52GIRZNUTTFIQPLANCNFSM4GKP6REQ>.
