### ISSUE TITLE
Fix pagination

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#33]

**Comment by nienna73** [comment]
@eddieantonio How is pagination broken? Is it still broken?

**Comment by eddieantonio** [comment]
Yes, it's still "broken". Really, this is a warning that shows up in the Django logs. I think the only thing that will fix it is if the `QuerySet` when rendering the main page is ordered, somehow.

**Comment by nienna73** [comment]
I'm not seeing this error anymore, but I didn't do anything to directly resolve it...I think. Could you try to replicate it when you have a moment @eddieantonio ?

**Comment by eddieantonio** [comment]
Yes, but please pester me about it again!

**Comment by nienna73** [comment]
I think this is fixed. I've started sorting the entries alphabetically by transcription. The paginator was warning that having an unsorted set would produce different results sometimes, so sorting the set seems to have solved it.

**Comment by eddieantonio** [comment]
Yep, simply sorting the query will get the paginator to stop complaining!
