### ISSUE TITLE
Fill in the few missing synthesized word-forms from the full layout for wâpamêw

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#336]
There are a few word-forms which are missing synthesizations for _wâpamêw_ - for demonstration purposes it would be good to generate them.

**Comment by aarppe** [comment]
Now that the various preverbed word-forms are again generated for the paradigms, we would want to add synthesizations for those forms as well.

**Comment by fbanados** [comment]
All word-forms generated for the extended paradigms of wâpamêw seem to have either synthesized or recorded sound entries.  Closing this.
