### ISSUE TITLE
Option to mark one recording (out of many) as best needed

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#337]
With in particular the spoken paradigms in mind, we'd need to have an opportunity to mark out a recording that is unequivocally good, or the best in the set, when there are many recordings which as a group are ok, if you can listen to them all and compare, but individually might be compromised as a single representation of the spoken form of a word. Examples of this can be heard below for _ê-kîsikâk_:

https://speech-db.altlab.app/maskwacis/search/?query=e-kisikak

In the context of the above, one would want to mark either of the two MAR recordings as objectively the best, to be shown when only one recording is possible.

**Comment by nienna73** [comment]
This has been solved on the speech-db side, but has yet to be resolved on the morphodict side. A new issue should be opened in morphodict for this feature.
