### ISSUE TITLE
Validate all words/phrases from the Maskwacîs dictionary

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#38]
Do this so that there's less work for the validators.

We will require some simple removal of vowel length

**Comment by aarppe** [comment]
The second pass at standardizing orthographically the MD content is completed, with the results available in the file:

MD_lex_std_anl_gen_norm_autoreview.txt

The script for generating the above file is provided below for reference:

cat MD_lex_std_anl_gen_norm.txt | gawk 'BEGIN { FS="\n"; RS=""; OFS="\t"; ORS="\n"; } { m=0; n_norm=0; line=""; delete norm; norms=""; split($1,f,"\t"); for(i=1; i<=NF; i++) { split($i,f,"\t"); anl=f[2]; gens=f[3]; n=split(f[3],gen,"; "); for(j=1; j<=n; j++) { cmp=gen[j]; gsub("â","a",cmp); gsub("ê","e",cmp); gsub("î","i",cmp); gsub("ô","o",cmp); sub("-","",cmp); if(tolower(f[1])==cmp) { if(!(gen[j] in norm)) norm[gen[j]]=gen[j]; gen[j]="*"gen[j]; m++; } line=sprintf("%s\t%s:%s", line,anl, gen[j]); } } for(k in norm) { norms=norms" + "k; n_norm++; } sub("^ \\+ ","",norms); if(norms=="") norms="+?"; line=sprintf("%i (%i/%i/%i)\t%s => %s\t%s\n", NR, n_norm, m, NF, f[1], norms, line); printf "%s", line; }' > MD_lex_std_anl_gen_norm_autoreview.txt

The first column indicates the row number in the CSV source for the Maskwacîs Dictionary.

The second column is crucial (cat MD_lex_std_anl_gen_norm_autoreview.txt | gawk '{ print $2; }' | sort | uniq -c | sort -nr | less):

4590 (1/1/1)
2956 (0/0/1)
 344 (2/2/2)
 282 (1/1/2)
 267 (1/2/2)
...

The third number indicates how many FST-analyses could be provided for the MD-original lexical entry, with the descriptive version of the FST (ignoring vowel length, and hyphens at prefix boundaries). The second number indicates how many of the FST-generated forms (based on the distinct FST-analyses) match, with orthographical relaxation, the MD-original lexical entry. The first number indicates how many distinct FST-generated forms match with vowel relaxation the MD-original lexical entry. If the first number =1, then however many analyses the MD-original lexical entry may have, even with orthographical relaxation in FST-analysis, the normative FST-generated forms are all the same.

Therefore, at this stage, 5362 MD-original lexical entries with a single FST-generated normative form can be orthographically normatized as such. (cat MD_lex_std_anl_gen_norm_autoreview.txt | grep '(1/' | wc -l).

Moreover, the 514 cases with 2 or more FST-generated forms require manual scrutiny (cat MD_lex_std_anl_gen_norm_autoreview.txt | egrep '\([2-9]/' | wc -l)

Finally, the 3110 cases that have not been able to be FST-analyzed require manual scrutiny (cat MD_lex_std_anl_gen_norm_autoreview.txt | grep '(0/' | wc -l). This mostly means that the FST lacks the lemma/stem in question, or that the FST may not incorporate the derivational/inflectional process manifested in the lexical entry. Nevertheless, these FST-unrecognized MD-original word forms can be incorporated in itwêwina, but they will not receive a linguistic analysis nor be amenable to paradigm generation.

**Comment by nienna73** [comment]
"Validate" and "all" are nebulous terms. Is this still something we're trying to do?

**Comment by aarppe** [comment]
This is comparable to autovalidation, in terms of what concerns the orthographical form. But what we should create a record of is those annotated word-forms which already occur in the Maskwacîs Dictionary, in which case a validation of the English translation is not needed (as that was validated at the time of inclusion within MD). This could be extracted from the MD spreadsheet, or the elicitation sheets, perhaps more easier from the former. In any event, the status of a word-form as already in MD should be recorded somewhere, so that those can be excluded from the validation task, with that focusing on the "new" words not yet in MD, and then the sentences.

**Comment by nienna73** [comment]
The remaining tasks for this issue are covered in #165. I'm marking this issue as a duplicate and closing it--all further discussion can take place in #165.
