### ISSUE TITLE
Orthographically normatize all Cree words/phrases in the recording database

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#41]
This is already described as a comment in #37, but should be kept as a separate issue as it is an alternative solution to spelling relaxation described in #37.

Once all Cree words/phrases in the recording database have been normatized (and in the dictionary source CSV for MD content as well), plus lemmas added for each Cree word (though that primarily deals with providing more audio snippets by finding recordings for all inflected forms sharing the same lemma), then likely spelling relaxation would not be needed anymore in retrieving audio snippets to itwêwina from the recording database.

So, normatization is the desired long-term solution. But before the normatization is completed (which requires an non-insubstantial amount of manual work), spelling relaxation is the interim solution.

I'll illustrate the status of orthographical consistency in the recording database. There are a three forms of `mikoskâcimêw`, as the lemma normatively spelled in Wolvengrey's dictionary and within the normative FST. These forms are the imperative, an unspecified actor form, and the lemma itself:

```
mikoskacim(!) 'Annoy him/her with disturbing talk!'
mikoskacimaw 'S/he is annoyed by senseless talk.'
mikoskacimêw 'S/he annoys him/her by senseless talk.'
```

All are recognized by the descriptive FST as well as itwêwina.

```
mikoskacim	mikoskâcimêw+V+TA+Imp+Imm+2Sg+3SgO	0.000000
mikoskacimaw	mikoskâcimêw+V+TA+Ind+Prs+X+3SgO	0.000000
mikoskacimêw	mikoskâcimêw+V+TA+Ind+Prs+3Sg+4Sg/PlO	0.000000
```

But all of them have at least one long-vowel marking missing (systematically the long `<â>`). Because of this discrepancy, none of these forms for which we do have a recording are presented as audio in itwêwina:

```
mikoskâcimêw+V+TA+Imp+Imm+2Sg+3SgO	mikoskâcim	0.000000
mikoskâcimêw+V+TA+Ind+Prs+X+3SgO	mikoskâcimâw	0.000000
mikoskâcimêw+V+TA+Ind+Prs+3Sg+4Sg/PlO	mikoskâcimêw	0.000000
```

We should be able to normatize these all, combining scripting (as is done already in a MD-normatization file for half of MD content), and manual work, as follows:

1. If the descriptive analysis to normative generation cycle provides just a single form, then that should apply.

2. If that cycle produces two or more normative forms, then manual scrutiny is required, but the forms to choose form have already been automatically generated.

3. If the descriptive FST does not provide an analysis, then either a lemma needs to be added to the FST and/or the transcription/spelling needs to be checked (most likely some missing vowel or additional or missing -h-).

**Comment by nienna73** [comment]
I believe everything we need to accomplish this task has been implemented in the speech-db, now it's just a matter of manually going through all the entries as we're doing with Rose and verifying the spelling of everything. Furthermore, itwêwina is already searching for exact spelling matches when querying speech-db for recording snippets.

@aarppe unless there are further features required to complete this task, I would consider it done.
