### ISSUE TITLE
Searching does not lead anywhere

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#42]
When searching for something, e.g. 'wolf':

![image](https://user-images.githubusercontent.com/15003407/50310833-7d798c00-0460-11e9-8a66-8f93b9000bfe.png)

... the result is an almost blank webpage with the code 501:

![image](https://user-images.githubusercontent.com/15003407/50310877-98e49700-0460-11e9-9454-5f9c5d5f4972.png)

Or is it that this works only through the administrative pages?

**Comment by eddieantonio** [comment]
This is because I never reimplemented search in Django >.<.

**Comment by nienna73** [comment]
Search leads somewhere now and the rest of the concerns regarding search functionality can be found in issue #94
