### ISSUE TITLE
In linguistic window, add a field for changing or correcting the RW semantic class

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#427]
Currently, there is no way for the linguist to correct or modify the semantic class. In particular in the beginning of the recording sessions, some MD words were placed under an incorrect semantic domain due to polysemy (e.g. _blanket_ for  _cloth_ placed under _snow_ as in _snow blanket_). So, we'd want to have a way of both seeing the semantic class(es) as well as have a field for modifying that class, when needed.

**Comment by fbanados** [comment]
![Screenshot 2024-08-27 at 10 44 07 AM](https://github.com/user-attachments/assets/6873ab14-a555-420f-889e-8ec3e5a749f4)

Change to "Full Linguistic Details"

**Comment by fbanados** [comment]
![Screenshot 2024-08-27 at 10 45 10 AM](https://github.com/user-attachments/assets/29741724-7fd7-4aba-9cf3-6d9b0c5efef4)

Make sure the button works as expected (go back to PREVIOUS page not to some random page)

**Comment by fbanados** [comment]
> ![Screenshot 2024-08-27 at 10 44 07 AM](https://private-user-images.githubusercontent.com/248151/361900702-6873ab14-a555-420f-889e-8ec3e5a749f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDY1MzUsIm5iZiI6MTcyNTA0NjIzNSwicGF0aCI6Ii8yNDgxNTEvMzYxOTAwNzAyLTY4NzNhYjE0LWE1NTUtNDIwZi04ODllLThlYzNlNWE3NDlmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxOTMwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZWFlMTEwNzNjOTc0N2YzZDJjZTcyZmZiOGZkYzBkYmEyOTZmZWU1ZmRkMjRmODgyYTYwMTAzNTJjNTc2NGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Vwqsz4CSo85F4SFd6YcmSZVZiuJJvwtYEDd6OuJ8QHI)
> 
> Change to "Full Linguistic Details"

done

**Comment by fbanados** [comment]
> ![Screenshot 2024-08-27 at 10 45 10 AM](https://private-user-images.githubusercontent.com/248151/361901000-29741724-7fd7-4aba-9cf3-6d9b0c5efef4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNDY1MzUsIm5iZiI6MTcyNTA0NjIzNSwicGF0aCI6Ii8yNDgxNTEvMzYxOTAxMDAwLTI5NzQxNzI0LTdmZDctNGFiYS05Y2YzLTZkOWIwYzVlZmVmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxOTMwMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYzFkM2Y3ZDE1ZTY0MGQ1YjU2YjBmMGJlMzlhMTMwODQ1ZmYwN2UxNTk3NjA2MzExMjg2YjI5NjBlOGQ3MDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iOgcn17mXD-Ubvz_srpsn8zdU3C6YSkN3lf_fipmBeY)
> 
> Make sure the button works as expected (go back to PREVIOUS page not to some random page)

See #115

**Comment by fbanados** [comment]
We have added a field to correct the RW semantic class.
