### ISSUE TITLE
Error when speaker code is missing

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#441]
When searching for <em>Edmonton</em> (under Maskwacîs), an error arises, cf.

https://speech-db.altlab.app/maskwacis/search/?query=Edmonton

It appears that there might be a recording (or more), but that/those are lacking a speaker code.

**Comment by pranjal080598** [comment]
Yes, I was able to fix this. Could you please retry? 

![image](https://github.com/UAlbertaALTLab/recording-validation-interface/assets/46446655/f1794f31-14f9-412b-877c-7caeb6b4ad62)
