### ISSUE TITLE
Pre-fill phrase updates on issues

### ISSUE THREAD

**Issue by fbanados** [UAlbertaALTLab/recording-validation-interface#443]
To simplify the linguist' task of editing issues for phrases, the update should be pre-filled with the current content.  It would simplify the correction by @aarppe

For example,
![Screenshot 2024-06-12 at 5 12 21 PM](https://github.com/UAlbertaALTLab/recording-validation-interface/assets/248151/1f12c31a-9144-42ea-8c7d-acd262d198d1)

**Comment by fbanados** [comment]
@aarppe I've implemented this behaviour in [this commit](https://github.com/UAlbertaALTLab/recording-validation-interface/commit/f6e7f9365c0fedf000d85b42792c447a7abdb737) and deployed it to production.

**Comment by aarppe** [comment]
@fbanados Great! Though something happened with the interface, with the CSS not being fully applied - see:
<img width="1392" alt="image" src="https://github.com/UAlbertaALTLab/recording-validation-interface/assets/15003407/0fbec44f-025d-4269-9795-65957efd3350">

Something similar happened previous when Jolene updated something in the interface, and it required a 10-minute fix-up from her.

We might want to look into why this happens, and what could be done to avoid it.

**Comment by aarppe** [comment]
@fbanados For full reference, preceding relevant work appears to have been discussed in #255 (if not fully implemented).

**Comment by fbanados** [comment]
The deployment script does not call the `collectstatic` command.  Once that's done, restarting the container sufficed to fix the issue.
