### ISSUE TITLE
Systematically wrong speaker code in some sessions

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#458]
In some sessions, the codes for some speakers seem to have gone systematically wrong for the entire session.

E.g., for  2018-04-25-AM-OFF-_, the snippets for HAR (Harley Simon) and BRI (Brian Lightning) seem to have been systematically reversed.

For now, I've created a 'Wrong speaker' issue in each such case, but that feels a bit repetitive if it applies across the whole session.

When reimporting the snippets, we might want to double-check that the speaker codes get assigned correctly as well. This does require, of course, familiarity with the voices of the various speakers.

**Comment by fbanados** [comment]
I've added a script to swap speakers for all recordings in a session, and tested it with the example session.  They should be ready for the next session.  Of course, the fix also removes the corresponding Wrong speaker issues as they should be solved with the change.

**Comment by fbanados** [comment]
We will provide no interface for this as it should not be a major occurrence.  But a linguist familiar with the voices can always notifiy me to run a script for a specific session and a particular pair of speakers to swap them.

**Comment by aarppe** [comment]
@fbanados Did you run this on  2018-04-25-AM-OFF? Since the BRI/HAR speaker codes still seemed to be swapped at my end.

**Comment by fbanados** [comment]
I thought I had, but I checked my local copy and it was different than the server, so I just run the script and it should be fine now.

**Comment by fbanados** [comment]
A fix is ready to deploy, but I'll wait until Daniel tells me he's done (or tomorrow morning, whichever happens first) to avoid issues.

Just as a side note, Speaker Code suggestion is only available from June 2021 onwards.  Word suggestions exist from almost the beginning.

**Comment by aarppe** [comment]
@fbanados Another session where this appears to be systematically the case is 2018-05-02-PM-OFF-_, where BRI and ARL appear to be swapped. I corrected this manually for one entry, _ýôski-_, but didn't touch the rest, though there appeared to be quite a deal for cases of 'Wrong speaker' marked.

**Comment by fbanados** [comment]
I will run the script to swap the speakers between BRI and ARL for that session, and ensure that the entry for ýôski-  remains as-is.

**Comment by fbanados** [comment]
Script ran successfully.
