### ISSUE TITLE
"Wrong speaker" suggestion list

### ISSUE THREAD

**Issue by fbanados** [UAlbertaALTLab/recording-validation-interface#459]
Should the suggestion list when a linguist marks a recording as having the wrong speaker be sorted by speaker code in alphabetical order?  Sometimes it is hard for me to find a speaker, but if linguists are used to the order it might not be worth changing the current behaviour.

**Comment by aarppe** [comment]
I had the impression that the order of speakers is based on how many sessions they had participated in, but actually I'm not entire sure if that is truly the case. If in session order, then it should start with MAR (Mary Jane "Jean" Littlechild) and LOU (Louise Wildcat), and so on. Nevertheless, the current order largely has the speakers who participated in many sessions before those who took part in fewer sessions, so it's worked for me sufficiently - though we could consider yet fixing it, according to some systematic principle, which isn't now apparently the case.

**Comment by fbanados** [comment]
Currently there is no guaranteed order, we use the default order given by the database, which could be just the order from first added to the database to last.

Since there's no need for this, I will just close the issue for now as won't fix, but if this becomes an issue eventually we can revisit it.
