### ISSUE TITLE
Adjust linking from morphodict to deal with various diacritics/accents

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#462]
Currently, morphodict will not retrieve recordings from Speech-DB, when the search involves certain diacritics such as the accented `<y>`, e.g. _nêhiyaw_ will not get audio, even when such do exist. This should be revised as follows:

- [x] accent (or not) on `<y>` should be irrelevant
- [x] macron, circumflex, or accent on the vowels `<a, i, o>` should be irrelevant; however vowels `<a, i, o>` without an accent/diacritic should not be combined with ones with those diacritics/accents
- [x] macron, circumflex, accent, or their absence, on the vowel `<e>` should be irrelevant

We could, of course, fix this by adjusting the transcriptions in Speech-DB to have accented y's when that is the case, but an interim/generic solution is nevertheless required.

These matching rules will vary from language to language.

**Comment by fbanados** [comment]
Note: There is language-specific code for moswachik trying to deal with the macrons that gets superseded by this feature, thus it is likely that a change on the morphodict side will also be required for moswacihk entries.  Needs to be checked before closing this issue.

**Comment by fbanados** [comment]
It seems that the moswachik code is already not working well: Currently, in itwewina, search for pēhtawēw does not generate sound files when marked moswachik only, even though there are 4 entries for Jean Okimasis in the speech-db database.

My guess is that pushing the current changes will fix the issue anyways, but I will check and otherwise set an issue in morphodict for that.

**Comment by fbanados** [comment]
Confirmed that this implementation fixes the moswacihk issue.  However, sometimes entries may appear more than once in result set. Working on it.

**Comment by fbanados** [comment]
Issue was wrong regex, as instead of, say, `asp(e|é|è|ê|ē)(y|ý)imowin`, regex for transcription should have been `^asp(e|é|è|ê|ē)(y|ý)imowin$`. Fixed.

**Comment by fbanados** [comment]
This code has been deployed to production and fixed morphodict without changes on that side.
