### ISSUE TITLE
Possibly reduce the number of audio snippets that are passed over to another application

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#466]
For some Cree words, there are oodles of recordings from multiple speakers. In such a case, we may want to limit the recordings that are passed over to another (morphodict) application such as itwêwina. Examples of such cases are _namôya_ and _waskic_, cf:

https://speech-db.altlab.app/maskwacis/segment/457
https://speech-db.altlab.app/maskwacis/segment/20505

When the number of available good recordings is over some threshold, let us say 10 recordings, we might show only one recording per speaker, unless that's below 10, in which case we could add a second recording per speaker until 10 snippets are reached, and then a third recording per speaker, and so forth. And if we haven't restricted to recordings to a single community, we'd want to ensure that there are recordings from all communities. Of course, one of the recordings has to be the starred one.

This could be implemented on the receiping app end as well, and I'm not entirely decided/sure which would be the better option.

**Comment by fbanados** [comment]
Part of the fixes I've made this morning makes sure that the default recording that appears on the speaker is actually the best one, because the sorting order in the code was doing the opposite (unless there was one recording, it wouldn't be the "best" one because it would sort by "is_best" and thus the best ones would end up in the end instead of the beginning)

**Comment by fbanados** [comment]
Ok!  It does look that namôya does not have a best recording, fyi.

**Comment by aarppe** [comment]
> does look that namôya does not have a best recording,

Picked one for now.

**Comment by fbanados** [comment]
Deployed
