### ISSUE TITLE
Wrong speaker code

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#470]
For the session `2018-03-07-AM-OFF,` the speaker code`BL2 `should rather be `BRI`.

**Comment by fbanados** [comment]
Is this a relabelling or a swap? (i.e. does `BRI` also need to be changed to `BL2`, or just `BL2` to `BRI`?)

**Comment by aarppe** [comment]
For now, it should just be a relabeling, of `BL2` to `BRI`, for that particular session.

**Comment by fbanados** [comment]
Relabelling performed.
