### ISSUE TITLE
Make speaker pages: /speakers/CODE

### ISSUE THREAD

**Issue by eddieantonio** [UAlbertaALTLab/recording-validation-interface#72]
Dynamically create pages for each speaker, including an overview/index page styled after http://altlab.ualberta.ca/maskwacis/Speakers/speakers.html

 - [ ] Add ability to upload speaker photo
 - [x] Add a speaker bio (English)
 - [x] Create index page with grid of speaker photos (exactly like http://altlab.ualberta.ca/maskwacis/Speakers/speakers.html)
 - [x] Dynamically create pages for each individual speaker
 - [x] Put a link on the homepage to find the speakers

The URL (relative to the webpage root) should be:

> `/speakers/:CODE`

where `:CODE` is the speaker's short identifier, e.g.,

> `/speakers/ARL`

will be the page for Arlene Makinaw.

**Comment by eddieantonio** [comment]
@aradu12 can you please take this on?

**Comment by nienna73** [comment]
Questions about this implementation:
1. Where does the speaker bio come from?
2. Do we want to upload a picture, or pull pictures from http://altlab.ualberta.ca/maskwacis/Speakers/speakers.html ?

**Comment by eddieantonio** [comment]
> 1. Where does the speaker bio come from?

They were recorded in both English and in nêhiyawêwin! I'm not sure if there's a transcription available. @atticusha will know more of the details!

> 2. Do we want to upload a picture, or pull pictures from http://altlab.ualberta.ca/maskwacis/Speakers/speakers.html?

I think the best thing to do would be to upload the pictures _from_ http://altlab.ualberta.ca/maskwacis/Speakers/speakers.html, but we can just pull the picture from there for now 😅

**Comment by nienna73** [comment]
I can likely pre-load the bios at the same time as I pre-load the other information about the speakers, if we want it in the DB, that is. Either way, I'll be patient on that front.

I found the pictures on the Google Drive. Should I just add them to the repo?

**Comment by nienna73** [comment]
@aarppe Does our information privacy agreement with the speakers say anything about where and how their information is stored?
I'm wondering if I can upload the speaker images to GitHub or if they need to live offline somewhere.

**Comment by aarppe** [comment]
We do have the right to make the speakers information (incl. pictures) available (via the consent forms), but I wouldn't necessarily make those available on GitHub, but preferably in a somewhat more private place - of course, anyone can download any speaker's picture, but we wouldn't be storing those files on a public site.

**Comment by nienna73** [comment]
This is 80% complete, pending the speaker bios.

If those are going to take a long time to get, I can modify the current speakers page to just show the speaker's name (when we have it) and their picture (when we have it) and then we can add the bio back in at a later date.

**Comment by aarppe** [comment]
There are annotated bios for 5 or 6 of the speakers, i.e. the English has been transcribed and the Cree delineated (by Daniel). The English (and Cree) passages have been delineated into utterances/sentences, so we can present those passages aligned, rather than the entire English or Cree passage. We (i.e. "someone") would need to assess these annotations and process them into a form that can be included on the bio pages. Perhaps these might be accessible in the validation interface per each Speaker as their own bios, which could then be edited for public use?

**Comment by nienna73** [comment]
How soon do you think we'll have access to the speaker bios?
Everything on my end is ready for them, from what I can tell, so I'd love to have that information go up the next time we update the live site.

As for speakers editing their own information, we currently don't have any way to associate a user with a speaker. I made #162 to address this concern and other issues that indicated we'd be needing an accounts page.

**Comment by aarppe** [comment]
@nienna73 how much of this is now done?

**Comment by nienna73** [comment]
While this page is technically broken at the moment, it does exist and is completely implemented. I don't think users need the ability to upload their own photo, though I can make that a file field in Django so we can more easily upload photos through the admin interface. I'll open other issues covering the current problems with the speakers page and this task is officially done.
