### ISSUE TITLE
Resolve issues in ELAN/TextGrid conversion

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#80]
Since there have been reports on the ELAN/TextGrid conversion potentially not having worked properly in all cases (#73), this needs to be examined. Solutions may entail revising the converter and/or revising the annotations appropriately.

**Comment by eddieantonio** [comment]
I think @nienna73  is doing this right now!

**Comment by nienna73** [comment]
I think this is done?
As far as I can tell, any remaining issues in the import process are not being caused by the `.eaf` file type.

**Comment by eddieantonio** [comment]
Yep, this is outdated since we are no longer using TextGrids :/
