### ISSUE TITLE
Extract transcriptions for training persephone

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#89]
Ran the following script which created transcriptions for the recording snippets (with graphemes separed by spaces) and stored them in `/data/av/persephone/SPEAKER/tr/ `(so organized into directories by speakers.

`sqlite3 /data/texts/recval/recval.sqlite3 'SELECT r.id as recording_id, r.speaker_id as speaker, p.transcription as transcription FROM validation_phrase p, validation_recording r WHERE r.phrase_id = p.id;' | gawk '{ tr=""; split($0,s,"|"); n=split(s[3],c,""); for(i=1; i<=n-1; i++) tr=tr sprintf("%s ", c[i]); tr=tr sprintf("%s\n", c[n]); if(s[2]!="") printf "%s", tr > "/data/av/persephone/"s[2]"/tr/"s[1]".tr"; }'`

Issue #88 indicates five erroneously code snippets.

What remains to be done is the extraction of the *.wav files in a similar fashion.

**Comment by aarppe** [comment]
Here's the code that copies the `*.wav` files from `/data/texts/maskwacis-recording-snippets/` to the appropriate speaker-specific directories under `/data/av/persephone/`:

`find /data/texts/maskwacis-recording-snippets/ -path *.wav | gawk 'BEGIN { while(("find /data/av/persephone/ -path *.tr" | getline)!=0) { match($0,"(/data/av/persephone/[^/]+/)tr/(.+)\\.tr$",f); path[f[2]]=f[1]; } } { match($0,"(/data/texts/maskwacis-recording-snippets/)(.+).wav$",f); if(f[2] in path) { system("cp "$0" "path[f[2]]"wav/"); n++; if(n/100==int(n/100)) printf "[%i] ",n > "/dev/stderr"; } } END { printf "==> %i\n", n > "/dev/stderr"; }'`

**Comment by nienna73** [comment]
Both of these extraction processes can be done from within the recording validation project. @eddieantonio implemented the `.wav` extraction and I more recently implemented the transcription portion of this task.

To generate the `.wav` files: `python manage.py importrecordings --wav --skip-db`
To generate the transcription files: `python manage.py writetranscriptions`

Generating the transcription files assumes that you've already imported all the relevant data into the DB and you've already created `.wav` files. These changes can be found in the `write-trans-files` branch and will be merged after investigating a few data oddities.
