### ISSUE TITLE
Validation interface mockups

### ISSUE THREAD

**Issue by aarppe** [UAlbertaALTLab/recording-validation-interface#91]
Here are some sketches about how the validation interface could work and look like, using the transcription of the "new" Cree word _ewaninstohtahk_ 'he misunderstands it' as an example case:

1. Presenting the unvalidated word _ewaninstohtahk_ with the translation 'he misunderstands it'. The spell-checker is used to provide ranked suggestions. For each of the suggestions, one can opt to see their linguistic analysis, lemma, and the English translation(s) of the lemma (and preverbs as well). None of the suggestions are relevant, so we want to allow the validator to edit the transcription.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/15003407/101130020-edd33680-35bf-11eb-9c80-bef0c01d3c5e.png">

2. Having added a hyphen to the transcription --> _e-waninstohtahk_, the spell-checker is used to provide ranked suggestions again, for which one can opt to see their linguistic analysis, lemma, and the English translation(s) of the lemma.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/15003407/101130681-27f10800-35c1-11eb-907d-e4c7293e1a6b.png">

Now, we think that the third suggestion _ê-wani-nistohtâhk_ might be right, but the translation of its lemma _nistohtâw_, 'He divides it into three. [MD] s/he divides s.t. in three [CW]', does not match with the original English translation 'he misunderstands it' received during the recording sessions.

3. Next, we add one more -i- to the transcription --> e-waninistohtahk, for which the spell-checker provides ranked suggestions. This time, the second suggestion _ê-wani-nisitohtahk_ seems promising, as its linguistic analysis, and the translations of the lemma nisitohtam and the preverb wani- match with the original English translation.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/15003407/101130880-8a4a0880-35c1-11eb-8c93-46e56df60785.png">

4. Satisfied with this standardization _ê-wani-nisitohtahk_, the transcription for this particular recording is classified as *standardized*, wit the date and time and the name/initials of the validator.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/15003407/101131011-d006d100-35c1-11eb-9884-c4b4a9bc7c3e.png">

5. The validation of the English translation still remains to be done (by a speaker/Elder).

Further notes:

1.	We need to allow for some word-forms that cannot be analyzed by the current computational model, primarily because the lemma/stem is not in the model or secondarily because the (rarer) inflected form has not been implemented in the model.
2.	In such a case, we have to allow for the manual entering of all the fields: a) the word-form, b) the linguistic analysis, and c) the lemma.
3.	Therefore, besides the automated provision of suggestions for the standardized word-form, linguistic analysis, and lemma, any one of these feels should be manually editable. However, such cases should be flagged with some special code for later scrutiny.
4.	For the status of the validation, there can be several values:
	a.	unvalidated
	b.	standardized (orthography)
		i.	with model
		ii.	manually without model (addition of lemma to model needed)
		iii.	second option needed
	c.	validated (translation) (speaker/Elder use).
5.	Instead of the spell-checker weights, we should use a modified edit-distance metric to rank the suggestions.
	a. adding/removing diacritics or hyphens, swapping glides w/y, or adding/removing aspirations -h- between vowel and consonant would have a weight of zero.
	b. inserting the vowel -i- between two consonants would have a half-weight (0.5).
	c. inserting/removing/swapping any other characters would have a normal weight of one.
6. Instead of the spell-checker, we could use a weighted descriptive analyzer.

**Comment by aarppe** [comment]
@nienna73 This issue has my first attempt at describing how the validation task (by a linguist) could work on the word-level.

**Comment by nienna73** [comment]
@aarppe This outline and flow of events seems to make sense to me. I've drafted some technical requirements based off our conversation and the description above:

1. The user must be able to log in using a username (and password?)
        a. Alternatively, the user must enter their name or initials before changes are saved
2. The user should be able to search for a term
3. The system should present the following for each search term:
        a. The Maskwacîs word
        b. The audio recording
        c. Transcription from the field
        d. Suggested terms from spellchecker
        e. MED as calculated by service
        f. Linguistic analysis and lemma from HFST
        g. Translation of each suggestion as provided by itwewina
4. The user should be able to manually make edits for the current version of the Cree spelling
5. The system should be able to store all past versions of Cree words and the user who made each change
6. The user should be able to accept suggested spellings as the new standard form
7. The system should be able to flag entries as: unvalidated, standardized with model, standardized without model, standardized pending review, or validated
8. The system should be able to calculate MED based on requirements above

I can create a new issue for each of these requirements once they're confirmed so we can keep track of how things are progressing.

**Comment by aarppe** [comment]
@nienna73 - Looks good - only a few comments below:

> 1. The user must be able to log in using a username (and password?)
>         a. Alternatively, the user must enter their name or initials before changes are saved
> 2. The user should be able to search for a term
> 3. The system should present the following for each search term:
>         a. The Maskwacîs word

Also, the English translation as stored in the annotations from the field notes. Note that sometimes the translation concerns an entirer sentence or phrase, not a single word. Words vs. sentences should be on separate tiers in the annotations, and as such identifiable.

>         b. The audio recording
>         c. Transcription from the field
>         d. Suggested terms from spellchecker
>         e. MED as calculated by service
>         f. Linguistic analysis and lemma from HFST
>         g. Translation of each suggestion as provided by itwewina

For future reference, eventually we might want to link in Maskwacîs Dictionary translations not yet included in itwêwina.

> 4. The user should be able to manually make edits for the current version of the Cree spelling
> 5. The system should be able to store all past versions of Cree words and the user who made each change
> 6. The user should be able to accept suggested spellings as the new standard form
> 7. The system should be able to flag entries as: unvalidated, standardized with model, standardized without model, standardized pending review, or validated

If the MED = 0 with some unique speller-suggestion, we might even consider an option of 'autostandardized',  with a separate field showing the spell-checker option for which MED = 0. Since something like 30-50% of the transcriptions meet this requirement, we could increase the amount of words that we can make provisionally available by a substantial amount straight off, pending gradually advancing manual review.

> 8. The system should be able to calculate MED based on requirements above

**Comment by nienna73** [comment]
Each of the user stories above now has its own issue to allow further discussion of each topic.
