### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/recording-validation-interface#94]
Related to Issue #42 

Search is visually implemented, but does not actually work.

The search interface should look something like:
<img width="430" alt="search" src="https://user-images.githubusercontent.com/28357720/103039111-45b0ed80-452d-11eb-9143-f0a454539dfc.png">

Most of the issues concerning how search items will be displayed have been described in Issue #93 
This issue is relating to the back-end or strictly code side of search, where the functionality needs to be implemented and return all relevant information for each entry, as specified in #93 .

**Comment by aarppe** [comment]
Concerning what one wants to accomplish with search, we would actually want to consider what the validators/standardizers will be looking up, when they're systematically going through the recorded materials. It won't really be the case that they'll figure out some individual recording and then process that, and after that look up another snippet, and again and again. Rather, we'd want to be able to look up all recordings with a particular status, maybe ones that may have been "assigned" to some particular person, and perhaps some combination of their orthographical form, recording session, Rapid Words semantic class, or some other criterion.

**Comment by nienna73** [comment]
I think all of those search scenarios are plausible and I can implement them, I'm now considering how to make all this functionality intuitive to the user. I think being able to search for a term is still a standard and expected functionality of search, so I can implement that. Then perhaps a tab-like view for showing "all" phrases, "validated" phrases, and "unvalidated" phrases. We don't store some of the criterion described above, like the Rapid Words semantic class, but I could potentially implement an advanced search for all other fields available in the Phrases model.

**Comment by nienna73** [comment]
I believe search is in a state of "good enough" for this project and any other tasks related to search are covered in #121 
For right now, users can filter based on session or status (though I believe status is rarely used). Everything else is related to advanced search.
