### ISSUE TITLE
Allow users to make edits to entries

### ISSUE THREAD

**Issue by nienna73** [UAlbertaALTLab/recording-validation-interface#95]
The user should be able to manually make edits for the current version of the Cree spelling

This issue assumes that each word has its own page with all the necessary information to make a relevant edit, as described in option 2 of Issue #93 

The edit screen could look something like:
<img width="431" alt="edit" src="https://user-images.githubusercontent.com/28357720/103039361-f0c1a700-452d-11eb-952b-f60a9e24f29b.png">

This also relates to Issue #18, adding diacritic buttons to transcription field.

Here, each field that can be changed would become an entry field in a form. The field should auto-populate with the current value(s) for each field and the information necessary to make the edit should remain visible.

Here is my understanding of how the information can be divided into edit-able, and non-editable:
Edit-able:
- Spelling of word
- Translation
- Lemma

Non-editable:
- Information provided by another service, i.e. suggestions from divvunspell, hfst, and itwêwina
This information needs to remain visible to the user doesn't have to recall important things.

This issue is related entirely to the front-end implementation of editing an entry. The back-end implementation is described in issue #96 .

**Comment by nienna73** [comment]
So far, the user can edit the transcription, translation, and analysis of each entry. I'm also thinking of a way to mark audio quality for each recording.

**Comment by aarppe** [comment]
The audio quality should build upon what we extract from the ELAN annotations already, and we could use perhaps precified values such as `bad`, `best`, `ok`, and perhaps an open comment that can be edited, if we want to be comprehensive.

**Comment by aarppe** [comment]
I'm wondering whether we should separate the lemma from the features, when representing (and storing) the linguistic analysis.

**Comment by nienna73** [comment]
This issue feels outdated given the new UI. Linguists still have access to this page and can edit the transcription, translation, and analysis, but no other user group is allowed to see this page.

@aarppe  and @eddieantonio should we close this issue and create a new, more relevant one when the time arrives? Or do you think we should continue building off of this issue?

**Comment by aarppe** [comment]
Yes, it is the linguists who should be able to edit all information, while the Language experts could edit the English translations, and the rest simply flag problematic cases. So, if this is implemented, then this could be considered closed, and whatever later development would be needed would warrant its own new issue.
